# nixpacks.toml
# Configuration to install ImageMagick on Railway

[phases.setup]
# Install delegate libraries FIRST (they must be present before ImageMagick is installed)
# This is crucial for format support - see Section 4.1 of deployment guide
aptPkgs = [
    # Delegate libraries for image format support (MUST come first!)
    "libjpeg-dev",          # JPEG support
    "libpng-dev",           # PNG support
    "libtiff-dev",          # TIFF support
    "libwebp-dev",          # WebP support
    "ghostscript",          # PDF support (critical for PDF to PNG conversion)
    "libgs-dev",            # Ghostscript development files
    
    # Now install ImageMagick (AFTER delegates)
    "imagemagick", 
    "libmagickwand-dev",    # Development headers for ImageMagick
    
    # Font dependencies for PDFKit to generate real PDFs
    "fontconfig",           # Essential for PDFKit font management
    "fonts-liberation",     # Base fonts for PDFKit
    "libcairo2-dev",       # Cairo graphics library for PDFKit
    "libpango1.0-dev"      # Pango text layout for PDFKit
]

# Note: libmagickwand-dev is crucial for proper ImageMagick functionality
# fontconfig and cairo/pango are essential for PDFKit to render fonts properly